[tool.black]
line-length = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.poetry]
name = "python-project-template"
version = "0.1.0"
description = ""
authors = ["KDH <ehdgua01@naver.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.4.2"
flake8 = "^3.8.3"
mypy = "^0.782"
pre-commit = "^2.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
